### Increase timeout
# @timeout = 600000

POST http://admin:2503@localhost:8080/rest/PADCHESTDB
Content-Type: application/xml

<query xmlns="http://basex.org/rest">
    <text><![CDATA[
      let $all-images := /Images/image

      let $all-labels :=
        for $image in $all-images
        let $labels := $image/Labels/Label/text()
        return $labels

      let $unique-labels := distinct-values($all-labels)

      let $frequencies :=
        for $unique in $unique-labels
        let $count :=
          count(
            for $label in $all-labels
            where $label = $unique
            return $label
          )
        order by $count descending
        return
          <label>
            <name>{$unique}</name>
            <count>{$count}</count>
          </label>

      return subsequence($frequencies, 1, 10)
  ]]></text>
</query>
